import Sudoku_board

def createScenario():
    user=raw_input("Choose a scenario. 1 for Easy, 2 for Medium, 3 for Hard (warning, takes a while). \n")
    if not (user=="1" or user=="2" or user=="3"):
        createScenario()
    if user=="1":
        createScenario1()
        return 1
    elif user=="2":
        createScenario2()
        return 2
    elif user=="3":
        createScenario3()
        return 3


def createScenario1():
    Sudoku_board.a1.setValue(4)
    Sudoku_board.a2.setValue(7)
    Sudoku_board.a3.setValue(2)
    Sudoku_board.a5.setValue(1)
    Sudoku_board.a6.setValue(5)
    Sudoku_board.b5.setValue(6)
    Sudoku_board.b7.setValue(4)
    Sudoku_board.b8.setValue(2)
    Sudoku_board.b9.setValue(7)
    Sudoku_board.c1.setValue(3)
    Sudoku_board.c3.setValue(8)
    Sudoku_board.c4.setValue(4)
    Sudoku_board.c7.setValue(1)
    Sudoku_board.c9.setValue(5)
    Sudoku_board.d2.setValue(8)
    Sudoku_board.d3.setValue(4)
    Sudoku_board.d6.setValue(3)
    Sudoku_board.d7.setValue(5)
    Sudoku_board.d9.setValue(2)
    Sudoku_board.e1.setValue(7)
    Sudoku_board.e5.setValue(2)
    Sudoku_board.e6.setValue(4)
    Sudoku_board.e8.setValue(1)
    Sudoku_board.e9.setValue(6)
    Sudoku_board.f1.setValue(6)
    Sudoku_board.f2.setValue(2)
    Sudoku_board.f5.setValue(5)
    Sudoku_board.f6.setValue(7)
    Sudoku_board.f7.setValue(3)
    Sudoku_board.f8.setValue(4)
    Sudoku_board.g2.setValue(3)
    Sudoku_board.g3.setValue(6)
    Sudoku_board.g4.setValue(2)
    Sudoku_board.g5.setValue(4)
    Sudoku_board.g7.setValue(7)
    Sudoku_board.h2.setValue(4)
    Sudoku_board.h4.setValue(5)
    Sudoku_board.h7.setValue(6)
    Sudoku_board.h8.setValue(3)
    Sudoku_board.h9.setValue(9)
    Sudoku_board.i1.setValue(5)
    Sudoku_board.i3.setValue(1)
    Sudoku_board.i4.setValue(7)
    Sudoku_board.i6.setValue(6)
    Sudoku_board.i8.setValue(8)
    
    
def createScenario2():
    Sudoku_board.b8.setValue(8)
    Sudoku_board.c8.setValue(4)
    Sudoku_board.d7.setValue(5)
    Sudoku_board.e8.setValue(1)
    Sudoku_board.f9.setValue(8)
    Sudoku_board.f8.setValue(6)
    Sudoku_board.g7.setValue(1)
    Sudoku_board.i9.setValue(4)
    Sudoku_board.a6.setValue(1)
    Sudoku_board.a5.setValue(6)
    Sudoku_board.c6.setValue(3)
    Sudoku_board.c5.setValue(8)
    Sudoku_board.c4.setValue(2)
    Sudoku_board.d6.setValue(8)
    Sudoku_board.f4.setValue(9)
    Sudoku_board.g6.setValue(9)
    Sudoku_board.g5.setValue(4)
    Sudoku_board.g4.setValue(5)
    Sudoku_board.i5.setValue(3)
    Sudoku_board.i4.setValue(1)
    Sudoku_board.a1.setValue(2)
    Sudoku_board.c3.setValue(7)
    Sudoku_board.d1.setValue(3)
    Sudoku_board.d2.setValue(7)
    Sudoku_board.e2.setValue(8)
    Sudoku_board.f3.setValue(2)
    Sudoku_board.g2.setValue(2)
    Sudoku_board.h2.setValue(6)
    
#createScenario2()


def createScenario3():
    Sudoku_board.a9.setValue(8)
    Sudoku_board.b1.setValue(9)
    Sudoku_board.b6.setValue(5)
    Sudoku_board.b7.setValue(7)
    Sudoku_board.c2.setValue(8)
    Sudoku_board.c3.setValue(1)
    Sudoku_board.c8.setValue(3)
    Sudoku_board.d2.setValue(5)
    Sudoku_board.d4.setValue(1)
    Sudoku_board.d8.setValue(6)
    Sudoku_board.e5.setValue(4)
    Sudoku_board.e7.setValue(9)
    Sudoku_board.f5.setValue(5)
    Sudoku_board.f6.setValue(7)
    Sudoku_board.g1.setValue(4)
    Sudoku_board.g5.setValue(7)
    Sudoku_board.g7.setValue(2)
    Sudoku_board.h2.setValue(1)
    Sudoku_board.h3.setValue(6)
    Sudoku_board.h4.setValue(3)
    Sudoku_board.i3.setValue(8)
    
#createScenario3()

